Name:           ros-kinetic-summit-x-gazebo
Version:        1.1.1
Release:        0%{?dist}
Summary:        ROS summit_x_gazebo package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/summit_x_gazebo
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kinetic-gazebo-ros
Requires:       ros-kinetic-roscpp
Requires:       ros-kinetic-std-msgs
Requires:       ros-kinetic-std-srvs
Requires:       ros-kinetic-summit-x-control
Requires:       ros-kinetic-summit-x-description
Requires:       ros-kinetic-summit-x-robot-control
Requires:       ros-kinetic-tf
Requires:       ros-kinetic-xacro
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-gazebo-ros
BuildRequires:  ros-kinetic-roscpp
BuildRequires:  ros-kinetic-std-msgs
BuildRequires:  ros-kinetic-std-srvs
BuildRequires:  ros-kinetic-summit-x-control
BuildRequires:  ros-kinetic-summit-x-description
BuildRequires:  ros-kinetic-summit-x-robot-control
BuildRequires:  ros-kinetic-tf
BuildRequires:  ros-kinetic-xacro

%description
Launch files and world files to start the models in gazebo

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Fri Aug 26 2016 Carlos Villar <cvillar@robotnik.es> - 1.1.1-0
- Autogenerated by Bloom

* Wed Aug 24 2016 Carlos Villar <cvillar@robotnik.es> - 1.1.0-0
- Autogenerated by Bloom

* Tue Jul 19 2016 Carlos Villar <cvillar@robotnik.es> - 1.0.6-0
- Autogenerated by Bloom

